# Generated by Django 4.0.1 on 2022-01-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last_name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('size', models.IntegerField(verbose_name='size')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('downloads', models.IntegerField(verbose_name='downloads')),
                ('media_url', models.CharField(max_length=255, verbose_name='media_url')),
                ('category', models.CharField(choices=[('IMG', 'IMAGE'), ('VID', 'VIDEO'), ('AUD', 'AUDIO'), ('FIL', 'FILE')], max_length=100, verbose_name='category')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.user')),
            ],
        ),
    ]
