# Generated by Django 4.0.1 on 2022-01-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_media_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
